
import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors

<<<<<<< HEAD
# KAVACH-AI Day 12: PDF Reporting Engine
=======
# Multimodal Deepfake Detection System Using Advanced Machine Learning Techniques Day 12: PDF Reporting Engine
>>>>>>> 7df14d1 (UI enhanced)
# Generates forensic reports for user download

REPORT_DIR = "data/reports"
os.makedirs(REPORT_DIR, exist_ok=True)

class PDFReportGenerator:
    def __init__(self, output_dir=REPORT_DIR):
        self.output_dir = output_dir

    def generate_report(self, task_id: str, scan_data: dict):
        """
        Generates a PDF forensic report.
        scan_data expected format:
        {
            "filename": "video.mp4",
            "verdict": "DEEPFAKE DETECTED",
            "confidence": "HIGH",
            "final_score": 0.98,
            "breakdown": {"video": 0.99, "audio": 0.1, "temporal": 0.8},
            "timestamp": "2024-..."
        }
        """
        filename = f"{task_id}_report.pdf"
        filepath = os.path.join(self.output_dir, filename)
        
        c = canvas.Canvas(filepath, pagesize=letter)
        width, height = letter
        
        # Header
        c.setFont("Helvetica-Bold", 24)
<<<<<<< HEAD
        c.drawString(50, height - 50, "KAVACH-AI Forensic Report")
=======
        c.drawString(50, height - 50, "Multimodal Deepfake Detection System Using Advanced Machine Learning Techniques Forensic Report")
>>>>>>> 7df14d1 (UI enhanced)
        
        c.setFont("Helvetica", 10)
        c.drawString(50, height - 70, f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        c.drawString(50, height - 85, f"Task ID: {task_id}")
        
        c.line(50, height - 100, width - 50, height - 100)
        
        # Verdict Section
        verdict = scan_data.get("verdict", "UNKNOWN")
        c.setFont("Helvetica-Bold", 18)
        
        if "DEEPFAKE" in verdict.upper():
            c.setFillColor(colors.red)
        elif "REAL" in verdict.upper():
            c.setFillColor(colors.green)
        else:
            c.setFillColor(colors.orange)
            
        c.drawString(50, height - 150, f"Verdict: {verdict}")
        c.setFillColor(colors.black)
        
        c.setFont("Helvetica", 14)
        c.drawString(50, height - 175, f"Confidence: {scan_data.get('confidence', 'N/A')}")
        c.drawString(50, height - 195, f"Probability Score: {scan_data.get('final_score', 0):.4f}")
        
        # Breakdown Section
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, height - 250, "Modality Analysis:")
        
        c.setFont("Helvetica", 12)
        y = height - 280
        breakdown = scan_data.get("breakdown", {})
        
        for modality, score in breakdown.items():
            bar_width = score * 200
            c.rect(200, y - 2, bar_width, 10, fill=1)
            c.drawString(50, y, f"{modality.replace('_', ' ').title()}:")
            c.drawString(410, y, f"{score:.2f}")
            y -= 30
            
        # Footer
        c.setFont("Helvetica-Oblique", 8)
<<<<<<< HEAD
        c.drawString(50, 50, "This report is generated by KAVACH-AI automated analysis system.")
=======
        c.drawString(50, 50, "This report is generated by Multimodal Deepfake Detection System Using Advanced Machine Learning Techniques automated analysis system.")
>>>>>>> 7df14d1 (UI enhanced)
        c.drawString(50, 40, "It does not constitute legal proof without human verification.")
        
        c.save()
        return filepath

# Global instance
pdf_gen = PDFReportGenerator()

def generate_pdf_report(scan_data: dict, output_path: str = None):
    # This wrapper matches the expected signature in interview.py
    # or other modules that might expect a standalone function.
    task_id = scan_data.get("task_id", f"report_{int(datetime.now().timestamp())}")
    return pdf_gen.generate_report(task_id, scan_data)

