apiVersion: apps/v1
kind: Deployment
metadata:
<<<<<<< HEAD
  name: kavach-backend
  namespace: kavach-ai
=======
  name: mmdds-backend
  namespace: Multimodal Deepfake Detection System Using Advanced Machine Learning Techniques
>>>>>>> 7df14d1 (UI enhanced)
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
<<<<<<< HEAD
        image: abisheik687/kavach-backend:v2.0
=======
        image: abisheik687/mmdds-backend:v2.0
>>>>>>> 7df14d1 (UI enhanced)
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        envFrom:
        - configMapRef:
<<<<<<< HEAD
            name: kavach-config
        - secretRef:
            name: kavach-secrets
=======
            name: mmdds-config
        - secretRef:
            name: mmdds-secrets
>>>>>>> 7df14d1 (UI enhanced)
        startupProbe:
          httpGet:
            path: /health
            port: 8000
          failureThreshold: 30
          periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
<<<<<<< HEAD
  name: kavach-hpa
  namespace: kavach-ai
=======
  name: mmdds-hpa
  namespace: Multimodal Deepfake Detection System Using Advanced Machine Learning Techniques
>>>>>>> 7df14d1 (UI enhanced)
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
<<<<<<< HEAD
    name: kavach-backend
=======
    name: mmdds-backend
>>>>>>> 7df14d1 (UI enhanced)
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
